In [28]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error

from mlp import MLP
from metrics import mse_loss, precision, recall, f1_score, confusion_matrix

In [29]:
# Load the dataset
data = load_iris()

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, test_size=0.3, random_state=42)

# Convert the training and testing sets into input and labels
train_input = X_train
test_input = X_test

# Initialize the StandardScaler
scaler = StandardScaler()

# Fit the scaler on the training data and transform both the training and testing data
train_input = scaler.fit_transform(train_input)
test_input = scaler.transform(test_input)


# One-hot encode the target labels
encoder = OneHotEncoder()
train_labels = encoder.fit_transform(y_train.reshape(-1, 1)).toarray()
test_labels = encoder.transform(y_test.reshape(-1, 1)).toarray()

In [49]:
mlp = MLP(4, layer_dims = [64, 64, 3], activationfuncs=[ "relu", "softmax"], learning_rate=0.0005)

In [50]:
epoch=1000
batch_size = 1
for i in range(epoch):
    outs = []
    for j in range(0,len(train_input), batch_size):
        x = train_input[j:j+batch_size]
        y = train_labels[j:j+batch_size]
        out = mlp(x.T)
        mlp.backpropagation(y.T, out)
        outs.append(out)
    if i%10 == 0:
        print("mse loss : ", mse_loss(train_labels, np.array(outs).reshape([105,3])))

mse loss :  0.21319867722053276
mse loss :  0.17460981291663782
mse loss :  0.14934478207032884
mse loss :  0.1308970545515343
mse loss :  0.11940023602040377
mse loss :  0.08711969759487712
mse loss :  0.07777267140822815
mse loss :  0.07623473849871427
mse loss :  0.07616775342305751
mse loss :  0.07614110800263982
mse loss :  0.07612130585440642
mse loss :  0.0761018248230622
mse loss :  0.07607956126862464
mse loss :  0.07605148616617716
mse loss :  0.07601332139319668
mse loss :  0.07595807182865248
mse loss :  0.07587451691515014
mse loss :  0.0757485482512086
mse loss :  0.07557515566751546
mse loss :  0.07537515610605484
mse loss :  0.07518768294481398
mse loss :  0.07504010714476887
mse loss :  0.07493091971080813
mse loss :  0.07483154581296955
mse loss :  0.0746968544973118
mse loss :  0.07439326265998872
mse loss :  0.06606949383875128
mse loss :  0.057437866727489725
mse loss :  0.032868251282596114
mse loss :  0.03211917691277429
mse loss :  0.03197126243146354
mse loss :

In [51]:
outs= []
for input, label in zip(test_input, y_test):
    out = mlp(input.reshape(4,1))
    outs.append(np.argmax(out))

confusion_matrix = confusion_matrix(y_test,outs)
precision        = precision(confusion_matrix)
recall           = recall(confusion_matrix)
f1_score         = f1_score(confusion_matrix)
print(confusion_matrix,":confusion_matrix")
print(precision,":precision")
print(recall,":recall")
print(f1_score,":f1_score")


12 0 arash
12 0 arash
[[19  0  0]
 [ 0 12  1]
 [ 0  0 13]] :confusion_matrix
1.0 :precision
1.0 :recall
1.0 :f1_score


In [ ]:
print(repr(mlp))

In [44]:
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split

# Load the wine dataset
data = load_wine()
X = data.data   # Features (inputs)
y = data.target # Target (outputs)

# Split the dataset into a training set and a test set
# test_size=0.2 means 20% of data is used for testing and 80% for training
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Now, X_train and y_train are the training inputs and outputs,
# and X_test and y_test are the testing inputs and outputs.
train_input = X_train
test_input = X_test

# Initialize the StandardScaler
scaler = StandardScaler()

# Fit the scaler on the training data and transform both the training and testing data
train_input = scaler.fit_transform(train_input)
test_input = scaler.transform(test_input)

# One-hot encode the target labels
encoder = OneHotEncoder()
train_labels = encoder.fit_transform(y_train.reshape(-1, 1)).toarray()
test_labels = encoder.transform(y_test.reshape(-1, 1)).toarray()

print(train_labels.shape)

epoch=1000

# mlp = MLP(13, layer_dims = [128, 64, 3], activationfuncs=["softmax", "softmax"], learning_rate=0.05)
mlp = MLP(13, layer_dims = [128, 64, 3], activationfuncs=["softmax", "softmax"], learning_rate=0.005)


for i in range(epoch):
    outs = []
    for x, y in zip(train_input, train_labels):
        out = mlp(x.reshape(13,1))
        mlp.backpropagation(y.reshape(3,1), out)
        outs.append(out)
    if i%10 == 0:
        print("mse loss : ", mse_loss(train_labels, np.array(outs).reshape([142,3])))

outs= []
for input, label in zip(train_input, y_train):
    out = mlp(input.reshape(13,1))
    # print(out)
    outs.append(np.argmax(out))

(142, 3)
mse loss :  0.23055273508753207
mse loss :  0.22200764630136868
mse loss :  0.2158174880009909
mse loss :  0.21188971762936137
mse loss :  0.20959638888890297
mse loss :  0.20817012769486504
mse loss :  0.20711280812443603
mse loss :  0.2061849264087133
mse loss :  0.2052863884236396
mse loss :  0.20437646338107487
mse loss :  0.2034368928611217
mse loss :  0.2024573226314541
mse loss :  0.20142992448067673
mse loss :  0.20034744060915813
mse loss :  0.19920244029327533
mse loss :  0.1979869936057387
mse loss :  0.19669248755681598
mse loss :  0.1953094961499617
mse loss :  0.19382768217031868
mse loss :  0.19223573156082013
mse loss :  0.1905213282547835
mse loss :  0.18867118130285104
mse loss :  0.18667112780877496
mse loss :  0.1845063626873139
mse loss :  0.18216188716608062
mse loss :  0.1796233036514625
mse loss :  0.17687809038815783
mse loss :  0.17391745609864556
mse loss :  0.17073879702021127
mse loss :  0.16734858860242421
mse loss :  0.1637651244004797
mse loss :

In [47]:
outs= []
for input, label in zip(test_input, y_test):
    out = mlp(input.reshape(13,1))
    # print(out)
    outs.append(np.argmax(out))


y_test-outs

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0], dtype=int64)

In [48]:
def batch_normalization(batch, gamma, beta, epsilon=1e-5):
    # Calculate mean and variance
    mean = np.mean(batch, axis=0)
    variance = np.var(batch, axis=0)
    
    # Normalize
    batch_normalized = (batch - mean) / np.sqrt(variance + epsilon)
    
    # Scale and shift
    batch_scaled_and_shifted = gamma * batch_normalized + beta
    
    return batch_scaled_and_shifted